# Generated by Django 5.2.6 on 2025-09-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name_cat',
        ),
    ]
