# Generated by Django 5.2.6 on 2025-09-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_news_name_news_description_news_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_cat',
            new_name='name',
        ),
    ]
