# Generated by Django 5.2.6 on 2025-09-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_name_cat_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
