# Generated by Django 5.2.6 on 2025-09-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
