# Generated by Django 5.2.6 on 2025-09-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
