# Generated by Django 5.2 on 2025-09-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_new_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
