# Generated by Django 5.2 on 2025-09-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_new_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
