# Generated by Django 5.2 on 2025-09-22 09:17

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_new_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
