# Generated by Django 5.2 on 2025-09-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_new_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='views',
            new_name='view',
        ),
    ]
