# Generated by Django 5.2.6 on 2025-09-22 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_new_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='view',
        ),
        migrations.AddField(
            model_name='new',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, related_name='news_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
