# Generated by Django 5.2.6 on 2025-09-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
