# Generated by Django 5.2.6 on 2025-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_ad_title_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
