# Generated by Django 5.2.6 on 2025-09-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_ad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='urgents/')),
            ],
        ),
    ]
