# Generated by Django 5.2.6 on 2025-09-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
