# Generated by Django 5.2.6 on 2025-10-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_urgent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_detail', to='home.category'),
        ),
        migrations.RemoveField(
            model_name='new',
            name='view',
        ),
        migrations.AddField(
            model_name='new',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
