# Generated by Django 5.2.6 on 2025-10-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_new_category_remove_new_view_new_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='summary_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
