# Generated by Django 5.2.6 on 2025-10-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_new_summary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
