# Generated by Django 5.2.6 on 2025-10-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_new_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='summary_description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
